# Copyright(C) 2026 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT

# Make sure calibration is persistent and models are available after ryzer exit
volume_mappings:
- "~/.cache/huggingface/lerobot/calibration/:/opt/hf-cache/lerobot/calibration"

docker_extra_run_flags:
- "$(for d in /dev/ttyACM* /dev/video*; do [ -e \"$d\" ] && printf -- '--device=%s ' \"$d\"; done)"
